add_newline = true

[conda]
disabled = true
symbol = ""

[directory]
truncate_to_repo = false
style = "dimmed white"
disabled = false

[aws]
disabled = true

[crystal]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[julia]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[php]
disabled = true

[terraform]
disabled = true

[zig]
disabled = true

[purescript]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true